name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10, 12, 14, 15]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Store node version variable
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"

      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-${{ steps.node.outputs.version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm test

      # Commented out until this action is added in organization settings
      # - name: Report coverage
      #   if: success()
      #   uses: codecov/codecov-action@v1
