name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12, 16, 18]

    name: Test (node-${{ matrix.node-version }}/${{ matrix.os }})

    steps:
      - if: runner.os == 'Linux'  # PhantomJS OpenSSL 1.1.1 vs 3.x Ubuntu 22+ compat
        run: echo "OPENSSL_CONF=/dev/null" >> "$GITHUB_ENV"
      - if: runner.os == 'Windows'  # Tests would fail LF vs CRLF linebreak-style
        run: git config --global core.autocrlf false && git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test

      # Commented out until this action is added in organization settings
      # - name: Report coverage
      #   if: success()
      #   uses: codecov/codecov-action@v1
